component_depth: 1
languages:
- java
exclude:
- ./bin/.*
- ./bin/weka/.*
- ./bin/weka/associations/.*
- ./bin/weka/associations/gsp/.*
- ./bin/weka/associations/gsp/messages/.*
- ./bin/weka/associations/messages/.*
- ./bin/weka/associations/tertius/.*
- ./bin/weka/attributeSelection/.*
- ./bin/weka/classifiers/.*
- ./bin/weka/classifiers/bayes/.*
- ./bin/weka/classifiers/bayes/blr/.*
- ./bin/weka/classifiers/bayes/net/.*
- ./bin/weka/classifiers/bayes/net/estimate/.*
- ./bin/weka/classifiers/bayes/net/icons/.*
- ./bin/weka/classifiers/bayes/net/search/.*
- ./bin/weka/classifiers/bayes/net/search/ci/.*
- ./bin/weka/classifiers/bayes/net/search/fixed/.*
- ./bin/weka/classifiers/bayes/net/search/global/.*
- ./bin/weka/classifiers/bayes/net/search/local/.*
- ./bin/weka/classifiers/data/.*
- ./bin/weka/classifiers/evaluation/.*
- ./bin/weka/classifiers/functions/.*
- ./bin/weka/classifiers/functions/neural/.*
- ./bin/weka/classifiers/functions/pace/.*
- ./bin/weka/classifiers/functions/supportVector/.*
- ./bin/weka/classifiers/lazy/.*
- ./bin/weka/classifiers/lazy/kstar/.*
- ./bin/weka/classifiers/meta/.*
- ./bin/weka/classifiers/meta/nestedDichotomies/.*
- ./bin/weka/classifiers/mi/.*
- ./bin/weka/classifiers/mi/supportVector/.*
- ./bin/weka/classifiers/misc/.*
- ./bin/weka/classifiers/pmml/.*
- ./bin/weka/classifiers/pmml/consumer/.*
- ./bin/weka/classifiers/pmml/data/.*
- ./bin/weka/classifiers/rules/.*
- ./bin/weka/classifiers/rules/part/.*
- ./bin/weka/classifiers/trees/.*
- ./bin/weka/classifiers/trees/adtree/.*
- ./bin/weka/classifiers/trees/ft/.*
- ./bin/weka/classifiers/trees/j48/.*
- ./bin/weka/classifiers/trees/lmt/.*
- ./bin/weka/classifiers/trees/m5/.*
- ./bin/weka/classifiers/xml/.*
- ./bin/weka/clusterers/.*
- ./bin/weka/clusterers/forOPTICSAndDBScan/.*
- ./bin/weka/clusterers/forOPTICSAndDBScan/DataObjects/.*
- ./bin/weka/clusterers/forOPTICSAndDBScan/Databases/.*
- ./bin/weka/clusterers/forOPTICSAndDBScan/OPTICS_GUI/.*
- ./bin/weka/clusterers/forOPTICSAndDBScan/OPTICS_GUI/Graphics/.*
- ./bin/weka/clusterers/forOPTICSAndDBScan/Utils/.*
- ./bin/weka/core/.*
- ./bin/weka/core/converters/.*
- ./bin/weka/core/data/.*
- ./bin/weka/core/logging/.*
- ./bin/weka/core/mathematicalexpression/.*
- ./bin/weka/core/matrix/.*
- ./bin/weka/core/neighboursearch/.*
- ./bin/weka/core/neighboursearch/balltrees/.*
- ./bin/weka/core/neighboursearch/covertrees/.*
- ./bin/weka/core/neighboursearch/kdtrees/.*
- ./bin/weka/core/pmml/.*
- ./bin/weka/core/stemmers/.*
- ./bin/weka/core/tokenizers/.*
- ./bin/weka/core/xml/.*
- ./bin/weka/datagenerators/.*
- ./bin/weka/datagenerators/classifiers/.*
- ./bin/weka/datagenerators/classifiers/classification/.*
- ./bin/weka/datagenerators/classifiers/regression/.*
- ./bin/weka/datagenerators/clusterers/.*
- ./bin/weka/estimators/.*
- ./bin/weka/experiment/.*
- ./bin/weka/experiment/xml/.*
- ./bin/weka/filters/.*
- ./bin/weka/filters/data/.*
- ./bin/weka/filters/supervised/.*
- ./bin/weka/filters/supervised/attribute/.*
- ./bin/weka/filters/supervised/instance/.*
- ./bin/weka/filters/unsupervised/.*
- ./bin/weka/filters/unsupervised/attribute/.*
- ./bin/weka/filters/unsupervised/instance/.*
- ./bin/weka/filters/unsupervised/instance/subsetbyexpression/.*
- ./bin/weka/gui/.*
- ./bin/weka/gui/arffviewer/.*
- ./bin/weka/gui/arffviewer/messages/.*
- ./bin/weka/gui/beans/.*
- ./bin/weka/gui/beans/icons/.*
- ./bin/weka/gui/beans/messages/.*
- ./bin/weka/gui/beans/xml/.*
- ./bin/weka/gui/beans/xml/messages/.*
- ./bin/weka/gui/boundaryvisualizer/.*
- ./bin/weka/gui/boundaryvisualizer/messages/.*
- ./bin/weka/gui/experiment/.*
- ./bin/weka/gui/experiment/messages/.*
- ./bin/weka/gui/explorer/.*
- ./bin/weka/gui/explorer/messages/.*
- ./bin/weka/gui/graphvisualizer/.*
- ./bin/weka/gui/graphvisualizer/icons/.*
- ./bin/weka/gui/graphvisualizer/messages/.*
- ./bin/weka/gui/hierarchyvisualizer/.*
- ./bin/weka/gui/hierarchyvisualizer/messages/.*
- ./bin/weka/gui/images/.*
- ./bin/weka/gui/messages/.*
- ./bin/weka/gui/sql/.*
- ./bin/weka/gui/sql/event/.*
- ./bin/weka/gui/sql/event/messages/.*
- ./bin/weka/gui/sql/messages/.*
- ./bin/weka/gui/streams/.*
- ./bin/weka/gui/streams/messages/.*
- ./bin/weka/gui/treevisualizer/.*
- ./bin/weka/gui/treevisualizer/messages/.*
- ./bin/weka/gui/visualize/.*
- ./bin/weka/gui/visualize/messages/.*
- ./bin/weka/gui/visualize/plugins/.*
- ./bin/weka/test/.*
- ./changelogs/.*
- ./data/.*
- ./doc/.*
- ./doc/weka/.*
- ./doc/weka/associations/.*
- ./doc/weka/associations/gsp/.*
- ./doc/weka/associations/tertius/.*
- ./doc/weka/attributeSelection/.*
- ./doc/weka/classifiers/.*
- ./doc/weka/classifiers/bayes/.*
- ./doc/weka/classifiers/bayes/blr/.*
- ./doc/weka/classifiers/bayes/net/.*
- ./doc/weka/classifiers/bayes/net/estimate/.*
- ./doc/weka/classifiers/bayes/net/search/.*
- ./doc/weka/classifiers/bayes/net/search/ci/.*
- ./doc/weka/classifiers/bayes/net/search/fixed/.*
- ./doc/weka/classifiers/bayes/net/search/global/.*
- ./doc/weka/classifiers/bayes/net/search/local/.*
- ./doc/weka/classifiers/evaluation/.*
- ./doc/weka/classifiers/functions/.*
- ./doc/weka/classifiers/functions/neural/.*
- ./doc/weka/classifiers/functions/pace/.*
- ./doc/weka/classifiers/functions/supportVector/.*
- ./doc/weka/classifiers/lazy/.*
- ./doc/weka/classifiers/lazy/kstar/.*
- ./doc/weka/classifiers/meta/.*
- ./doc/weka/classifiers/meta/nestedDichotomies/.*
- ./doc/weka/classifiers/mi/.*
- ./doc/weka/classifiers/mi/supportVector/.*
- ./doc/weka/classifiers/misc/.*
- ./doc/weka/classifiers/pmml/.*
- ./doc/weka/classifiers/pmml/consumer/.*
- ./doc/weka/classifiers/rules/.*
- ./doc/weka/classifiers/rules/part/.*
- ./doc/weka/classifiers/trees/.*
- ./doc/weka/classifiers/trees/adtree/.*
- ./doc/weka/classifiers/trees/ft/.*
- ./doc/weka/classifiers/trees/j48/.*
- ./doc/weka/classifiers/trees/lmt/.*
- ./doc/weka/classifiers/trees/m5/.*
- ./doc/weka/classifiers/xml/.*
- ./doc/weka/clusterers/.*
- ./doc/weka/clusterers/forOPTICSAndDBScan/.*
- ./doc/weka/clusterers/forOPTICSAndDBScan/DataObjects/.*
- ./doc/weka/clusterers/forOPTICSAndDBScan/Databases/.*
- ./doc/weka/clusterers/forOPTICSAndDBScan/OPTICS_GUI/.*
- ./doc/weka/clusterers/forOPTICSAndDBScan/Utils/.*
- ./doc/weka/core/.*
- ./doc/weka/core/converters/.*
- ./doc/weka/core/logging/.*
- ./doc/weka/core/mathematicalexpression/.*
- ./doc/weka/core/matrix/.*
- ./doc/weka/core/neighboursearch/.*
- ./doc/weka/core/neighboursearch/balltrees/.*
- ./doc/weka/core/neighboursearch/covertrees/.*
- ./doc/weka/core/neighboursearch/kdtrees/.*
- ./doc/weka/core/pmml/.*
- ./doc/weka/core/stemmers/.*
- ./doc/weka/core/tokenizers/.*
- ./doc/weka/core/xml/.*
- ./doc/weka/datagenerators/.*
- ./doc/weka/datagenerators/classifiers/.*
- ./doc/weka/datagenerators/classifiers/classification/.*
- ./doc/weka/datagenerators/classifiers/regression/.*
- ./doc/weka/datagenerators/clusterers/.*
- ./doc/weka/estimators/.*
- ./doc/weka/experiment/.*
- ./doc/weka/experiment/xml/.*
- ./doc/weka/filters/.*
- ./doc/weka/filters/supervised/.*
- ./doc/weka/filters/supervised/attribute/.*
- ./doc/weka/filters/supervised/instance/.*
- ./doc/weka/filters/unsupervised/.*
- ./doc/weka/filters/unsupervised/attribute/.*
- ./doc/weka/filters/unsupervised/instance/.*
- ./doc/weka/filters/unsupervised/instance/subsetbyexpression/.*
- ./doc/weka/gui/.*
- ./doc/weka/gui/arffviewer/.*
- ./doc/weka/gui/beans/.*
- ./doc/weka/gui/beans/xml/.*
- ./doc/weka/gui/boundaryvisualizer/.*
- ./doc/weka/gui/experiment/.*
- ./doc/weka/gui/explorer/.*
- ./doc/weka/gui/graphvisualizer/.*
- ./doc/weka/gui/hierarchyvisualizer/.*
- ./doc/weka/gui/sql/.*
- ./doc/weka/gui/sql/event/.*
- ./doc/weka/gui/streams/.*
- ./doc/weka/gui/treevisualizer/.*
- ./doc/weka/gui/visualize/.*
- ./doc/weka/gui/visualize/plugins/.*
